"""Type stubs for the native module.

Hand-written rather than generated: it is a dozen lines, and pyo3-stub-gen
would be another build-time dependency for teammates to install.
"""

from typing import Optional

class Something:
    """Facade over the local or remote backend.

    Constructing it performs the version handshake, so a misconfigured client
    fails here rather than on its first call.
    """

    def __new__(cls, mode: Optional[str] = None) -> "Something": ...
    def ping(self) -> str: ...
    @property
    def negotiated_version(self) -> int: ...
    @property
    def server_build(self) -> str: ...
    def __repr__(self) -> str: ...

class SomethingError(Exception): ...
class IncompatibleError(SomethingError): ...
class TransportError(SomethingError): ...
class ServerError(SomethingError): ...
